title = "Aperios"
baseURL = "https://aperios.net/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

enableRobotsTXT = true


[markup.goldmark.parser.attribute]
  block = true


[sitemap]
  changeFreq = "monthly"
  filename = "sitemap.xml"
  priority = 1.0
  

[params]
  text_color = ""
  author = ""
  background_color_class = "bg-black"
  custom_css = ["css/main.css"]
  recent_posts_number = 0


[[menu.main]]
  name = "About"
  weight = 101
  url = "/about/"
[[menu.main]]
  name = "Contact"
  weight = 101
  url = "/about/#contact-us"
